### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by moltar** [prismicio/prismic-javascript#18]
Not sure if this is the lib error, or my code.

Express controller code:

```js
router.get('/', (req, res, next) => {
  return req.prismic.api
    .query('')
    .then((posts) => {
      res.render('blog/index', {
        title: 'Blog',
        posts: posts
      })
    })
    .catch(next)
})
```

Now, disable connection on the computer and try to access the route:

> (node:8251) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): FetchError: request to http://foo.prismic.io/api?access_token=... failed, reason: getaddrinfo ENOTFOUND foo.prismic.io foo.prismic.io:80

> (node:8251) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Manc** [comment]
I am also getting a `UnhandledPromiseRejectionWarning` if something goes wrong (e.g. wrong API key). I've been looking through my code for ages to find out where I may have missed a `catch`, but can't find anything. My application handles the exception successfully, but I'm still getting the warning. Although this is not a urgent problem, it might break the application in future Node versions as the warning suggests. Is it possible that the Prismic library causes the warning?

**Comment by srenault** [comment]
Hi, I'm going to look at it.

**Comment by Sxw1212** [comment]
Hi,

I also stumbled upon this problem in production. It's not a major issue, but it would be nice if a second look could be taken.

Unfortunately, the only logs I have for this are duplicates of

```
(node:15) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 13): [object Object]
```

**Comment by madhums** [comment]
Same problem here! Is there anyway we can use non-minified version for development? It's hard to debug these kind of issues if minified versions are meant to be used on the server side @srenault Any updates?

**Comment by Trolleymusic** [comment]
@madhums - you can specifically reference the non-minified file in the import, eg use:

```
import Prismic from 'prismic-javascript/dist/prismic-javascript.js'
```

instead of

```
import Prismic from 'prismic-javascript'
```

Then when debugging in-browser the non-minified version maps directly onto the typescript files

**Comment by j-sziegaud** [comment]
Hi, the issue still occurs on my end. While i can catch one promiseRejection on a prismic-api-call, there are several unhandled promiserejections emitted.

**Comment by timuric** [comment]
@moltar Looks like an issue with your code. You forgot to add ```return```statement  in your ```then``` method. Otherwise there is no way for ```.catch(next)``` to collect the rejection, since your ```then``` is returning ```undefined```

**Comment by karlbateman** [comment]
I've also got the following unhandled rejection:
```
UnhandledPromiseRejectionWarning: Error: Unexpected status code [400] on URL {PRISMIC_URL}
```

**Comment by arnaudlewis** [comment]
it'll be fixed in the new release today ;)

**Comment by BramDecuypere** [comment]
I still get these sometimes, and don't really have an idea on how to fix them.
Build a simple script that loops over and does a request to get some data....

https://github.com/BramDecuypere/loop-over-requests

Just keep running it multiple times and you will get either of 2 responses:
- 429 --> logically, your service gets tired of my requests, which I understand after this amount
- ENOTFOUND --> I have no clue what these are doing here? Is it something that is happening inside of node/node-fetch? Is it my code? Or the prismic service?

Just run the linked repo in 2 seperate terminals at the same time. And one of them will get this issue. Any insights would be great!
