### ISSUE TITLE
"slug" is mentioned in Document.ts but does not appear in the api search response.

### ISSUE THREAD

**Issue by danielhuggins** [prismicio/prismic-javascript#37]
There is a "slugs" property, but no singular "slug" property.

**Comment by danielhuggins** [comment]
Uh, also in Document.ts alternateLanguages, firstPublicationDate and lastPublicationDate are given as camelCase but in the search response they are snake_case. Bug?

**Comment by levimykel** [comment]
Hi @danielhuggins, thanks for reporting this. Someone will look into this as soon as we are able.

**Comment by danielhuggins** [comment]
Yeah there's also the problem that "Document" is being confused for the
browser "Document" type.

**Comment by despairblue** [comment]
@danielhuggins @levimykel #45 fixes this. Would be awesome if someone could merge that.

**Comment by despairblue** [comment]
Oh #38 is also fixing this and the approach in #39 is also really nice and similar to how the mongodb driver is typed.

**Comment by srenault** [comment]
Fixed in https://github.com/prismicio/prismic-javascript/pull/48

**Comment by despairblue** [comment]
@srenault Sorry but that does not fix that the document exported is still the one coming from dom.d.ts because the imports are missing that the other PRs add.

Should I open another issue for that?

**Comment by srenault** [comment]
Hey @despairblue. How can I reproduce your issue?
