### ISSUE TITLE
I keep getting this CORS issue

### ISSUE THREAD

**Issue by ericraio** [prismicio/prismic-javascript#61]
I just released my website and I keep getting this CORS issue from prismic. I don't know where to turn for this.

Any idea?

`
Failed to load https://automate-your-brand.prismic.io/app/authenticated/v2: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://automateyourbrand.com' is therefore not allowed access. The response had HTTP status code 401. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
`

**Comment by birkir** [comment]
Same for me.

I see no options in the Prismic UI to allow a specific set of domains for the preview control.

One of the previews has the domain for me, I thought that would be enough

**Comment by Duaner** [comment]
Hello @ericraio and @birkir by adding the domain of your website to the settings / Previews. This should be fixed.

**Comment by adamjgrant** [comment]
Tried that. Still getting this error message.

Why not just allow for passing in `master` as the ref rather than requiring a second API call to find out what the master ref is?

**Comment by tylermcrobert** [comment]
Happening to me as well. I'm using netlify and when I set the preview URL to my CNAME domain, it does not work.

**Comment by rjmccluskey** [comment]
I'm also having this issue. I have the url configured in the previews settings.

I'm using the gatsby plugin and my site is hosted on netlify

**Comment by goldenshun** [comment]
I see this error as well but only when I pass a preview token via the `Prismic-Ref` header. I am also using the `/graphql` endpoint, not sure if that is related.

**Comment by HannesArni** [comment]
I encountered this error becuase I added an extra slash at the end of the client url, removing that slash fixed the issue

**Comment by cannap** [comment]
i have the same 

Access to fetch at 'https://xxxxx.prismic.io/graphql/' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

i use apollo for nuxt 

  apollo: {
    clientConfigs: {
      default: {
        httpEndpoint: process.env.PRISMIC
        //   browserHttpEndpoint: '/graphql'
      }
    }
  }

PRISMIC=https://xxxx.prismic.io/graphql

**Comment by cannap** [comment]
i fixed it i just followed the way he makes https://github.com/markperez1904/personal-website
